### ISSUE TITLE
Regression in v3.7.7

### ISSUE THREAD

**Issue by hacknug** [paulober/pyboard-serial-com#5]
## What are the steps to reproduce this issue?

Not sure there is any steps to reproduce as it happens during vscode startup when the extension is enabled.

## What happens?
Extension seems to throw during initialization. Regression was introduced in v3.7.7 since everything seems to work fine in v3.7.6.

## Any logs, error output, etc?
*(To get extension logs see Terminal > Output > Extension Host and copy output concerning pico-w-go or micropico)*
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

```
2024-05-30 22:50:40.794 [error] Activating extension paulober.pico-w-go failed due to an error:
2024-05-30 22:50:40.794 [error] Error: spawn Unknown system error -86
  at ChildProcess.spawn (node:internal/child_process:414:11)  at Object.spawn (node:child_process:799:9)
  at new e (/Users/nestor/.vscode/extensions/paulober.pico-w-go-3.7.7-darwin-x64/dist/extension.cjs:1:5181)  at Wh.activate (/Users/nestor/.vscode/extensions/paulober.pico-w-go-3.7.7-darwin-x64/dist/extension.cjs:8:86711)
  at async exports.activate (/Users/nestor/.vscode/extensions/paulober.pico-w-go-3.7.7-darwin-x64/dist/extension.cjs:8:105526)  at async h.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:6281)
  at async h.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:6244)  at async h.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:5701)
```

## Any other comments?

I can provide more details if necessary since it seems I can reproduce it 100% of times just by launching the editor.

## Which version of MicroPico are you using?

v3.7.7

## Support info

```
Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.5.0
```

**Comment by paulober** [comment]
Should be fixed with [release v3.0.9](https://github.com/paulober/pyboard-serial-com/releases/tag/v3.0.9).

**Comment by hacknug** [comment]
I can confirm it is now fixed. Thank you for such a quick update! 💖
